### ISSUE TITLE
generic suggestions

### ISSUE THREAD

**Issue by Yaser-Amiri** [alirezarpi/air-net-led#1]
Dear Alireza, I reviewed your code and there are some points that it's better to consider them.

https://github.com/alirezarpi/air-net-led/blob/97587734e8b512f1fc950b8411624ba2b331efbc/air-net-led.sh#L13
It's better to check exit code of Ping instead of reading its stdout and stderr.
The first ping request is not trusted even in local networks (you know in Iran internet connections are not reliable at all). It's better to increase ping requests and sleep time too.
You can add more flexibility to your script with allowing the user to change ping requests count and server. (I suggest to use environment variables and setting them in systemd service file)

**Comment by alirezarpi** [comment]
Thank you for your comment @Yaser-Amiri, ping request number makes the script more accurate so it is ok that I set the number to 1, For now the flexibility is limited because this script mainly used as service at system boot.
The exit code check was a very good suggestion I will absolutely add this to the main script :)
I will upload the flexible script as `air-net-led-flex.sh` as you asked, that is runnable from terminal with your **targets** and **count requests**.
thank you again
